name: Run Docker Compose

on: push

jobs:
  run-docker:
    runs-on: self-hosted

    steps:
      - name: Run docker compose
        run: |
          cd /home/cybersecurity/Desktop/Shatha-docker2
          docker compose up -d
